### PR TITLE
add datalayer and schema layer to make contract upgradable

### PR DESCRIPTION
**Pull request by inovizz**

### CODE REVIEW

**Comment by nrchandan** [comment]
New PR to be raised by Nishant.

**Comment by srikumarks** [comment]
Any notes on *why* this change results in an upgradeable contract?

**Comment by inovizz** [comment]
@srikumarks The solution I implemented was incorrect and hence we discarded it.

**Comment by nrchandan** [comment]
Here are two commits towards that goal:
https://github.com/Imaginea/lms/pull/73 (merged)
https://github.com/Imaginea/lms/pull/76 (still under review)

This approach is inspired by this blog entry: https://blog.colony.io/writing-upgradeable-contracts-in-solidity-6743f0eecc88
Colony.io has an interesting goal. They are trying to create a distributed company for doing all sorts of commercial activity. Somewhere between traditional services company and freelancing.

**Comment by srikumarks** [comment]
Thanks Chandan. Just became aware of Colony today. It comes across as a pcoin, but at global scale. Will be interesting to see where it goes. I read recently that with monetary benefits from day 1, the chicken-vs-egg problem of boot strapping a problem is much more tractable, as some of the blockchain startups are finding. So colony may see some success here.

**Pull request closed without merging**
