### PR TITLE
Replace throw with revert() and fix issue#111

### PR DESCRIPTION
**Pull request by neeldhwaj**

### CODE REVIEW

**Comment by inovizz** [comment]
package-lock.json should not be included, please remove it and also add version numbers in travis.yml as discussed.

**Comment by jdar** [comment]
Hi Neeldhwaj,

I just tried to make a quick Dockerfile matching the travis.ci versions you outlined. 

Any idea why this doesn't work?  (FYI, I think Debian and Ubuntu are close enough that the OS isn't the issue...)


########### DOCKERFILE ########
FROM node:6.11.0

ARG CACHEBUST=3
RUN git clone https://github.com/neeldhwaj/lms /lms

WORKDIR /lms

RUN npm install -g truffle@3.4.9

RUN npm install -g ethereumjs-testrpc@4.1.0

RUN npm install -g solium@0.5.5

RUN npm install

RUN truffle compile


########################

errors are:

Step 9/9 : RUN truffle compile
 ---> Running in 2a07ff4ac3b4
Compiling ./contracts/BooksLibrary.sol...
Compiling ./contracts/DataStore.sol...
Compiling ./contracts/LMS.sol...
Compiling ./contracts/MembersLibrary.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/OrgLibrary.sol...
Compiling ./contracts/Organisation.sol...
Compiling ./contracts/OrganisationInterface.sol...
Compiling ./contracts/Parent.sol...
Compiling ./contracts/helper_contracts/StringLib.sol...
Compiling ./contracts/helper_contracts/strings.sol...
Compiling ./contracts/helper_contracts/zeppelin/lifecycle/Killable.sol...
Compiling ./contracts/helper_contracts/zeppelin/ownership/Ownable.sol...

Compilation warnings encountered:

/lms/contracts/helper_contracts/zeppelin/ownership/Ownable.sol:19:7: Warning: "throw" is deprecated in favour of "revert()", "require()" and "assert()".
      throw;
      ^---^
,/lms/contracts/helper_contracts/StringLib.sol:65:13: Warning: "throw" is deprecated in favour of "revert()", "require()" and "assert()".
            throw;
            ^---^
,/lms/contracts/helper_contracts/StringLib.sol:76:17: Warning: "throw" is deprecated in favour of "revert()", "require()" and "assert()".
                throw;
                ^---^
,/lms/contracts/Organisation.sol:156:13: Warning: "throw" is deprecated in favour of "revert()", "require()" and "assert()".
            throw;
            ^---^
,/lms/contracts/OrganisationInterface.sol:34:9: Warning: "throw" is deprecated in favour of "revert()", "require()" and "assert()".
        throw;
        ^---^
,/lms/contracts/Parent.sol:47:13: Warning: "throw" is deprecated in favour of "revert()", "require()" and "assert()".
            throw;
            ^---^
,/lms/contracts/helper_contracts/strings.sol:160:14: Warning: This declaration shadows an existing declaration.
        for (uint len = 0; ptr < end; len++) {
             ^------^
/lms/contracts/helper_contracts/strings.sol:156:5: The shadowed declaration is here:
    function len(slice self) internal returns (uint) {
    ^
Spanning multiple lines.

,/lms/contracts/helper_contracts/strings.sol:250:9: Warning: This declaration shadows an existing declaration.
        uint len;

... and more like this.

**Comment by jdar** [comment]
UPDATE:

OK, i see now. Those are merely warnings. My bad.

also I realized that there are fewer warnings when using branch. 'issue#111'

**Comment by inovizz** [comment]
Looks good for now, we need work on warnings as well. I'll take care of them in PR #105.

**Pull request merged**
